# Site settings
title: Cong Depeng | 从德鹏
email: congdepeng@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Java, Python, Linux 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://congdepeng.github.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
